# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js deploy github-pages CI


on:
   workflow_run:
     workflows: ["Node.js CI"]
     types: [completed] #requested

jobs:
   on-success:
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'success' }}
     strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/  

     steps:
       - uses: actions/checkout@v2
       - name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v2
         with:
            node-version: ${{ matrix.node-version }}
       - run: echo "First workflow was a success"
       - run: git config user.email "jasmin.kling93@gmail.com" && git config user.name "jkling2"
       - run: npm ci
       - run: npm run deploy

   on-failure:
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'failure' }}
     steps:
       - run: echo "First workflow was a failure"
